dev:
	python3 -m venv venv/
	. venv/bin/activate && pip install -r requirements.txt
	. venv/bin/activate && fastapi dev main.py

dev-windows:
	python -m venv venv/
	. venv/Scripts/activate && pip install -r requirements.ini
	. venv/Scripts/activate && fastapi dev main.py

